### PR TITLE
Css positioning

### PR DESCRIPTION
**Pull request by ClintonEnyinna**

### CODE REVIEW

**Comment by kobiyoyo** [comment]
### Pull Request under the review by Adama Chubiyojo Desmond (TSE)

**Comment by kobiyoyo** [comment]
## Hi Team 
#### Your project looks :+1: amazing readme file, so descriptive!
#### Kindly recommended check HTML markup with this [validator](https://validator.w3.org/#validate_by_upload). Now it shows errors in your project. 

### Page structure

#### Navigation bar

- [ ] It should have least three embedded images on the rightmost part of the navbar that represent icons and/or an avatar.

#### Video
- [ ] please add a share button
### Make changes and submit another code review request.
*Happy coding*

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
I kindly recommend fixing the above errors.

**Comment by moinkhanif** [comment]
Hey Chubi, we have made the required changes.

**Comment by kobiyoyo** [comment]
### Good Job  Team    on correcting the HTML errors.
#### However, there is still one more thing to do.
### Page structure
#### Video
- [ ] please add a share button.
### Make changes and submit another code review request.
*Happy coding*

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
### Good Job  Team    on correcting the HTML errors.
#### However, there is still one more thing to do.
### Page structure
#### Video
- [ ] please add a share button.(beneath the video the "**Share**" should be a button)
### Make changes and submit another code review request.

**Review by imhta — APPROVED** [review]
# Project Approved 👍 

### Hello team, 👋 You have done great job with this project. 👏 



----
#### Don't forgot to sumbit project completion form
 **Pon Muthu Selvam N**
Feel free contact me 
[Github //@imhta](https://github.com/imhta) | [Twitter //@nponmuthuselvam](https://twitter.com/ponmuthuselvam)

**Pull request merged**
